name = "my-app"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "v18.17.1"

[site]
bucket = ".vercel/output/static"

