name = "my-app"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20.16.0"

[site]
bucket = ".vercel/output/static"

# Add this line to specify the Pages build output directory
pages_build_output_dir = ".vercel/output/static"